[build_system]
requires= ["setuptools>=42.0","wheel"]
buils_backend="setuptools.buils_meta"

[tool.pytest.ini_options]
testpaths = [
    "tests"
    ]

[tool.mypy]
mypy_path="src"
ignore_missing_imports= true